id: I99F642E9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T04:11:07+00:00'
last_modified: '2022-06-08T17:38:46.698321+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2DB25437
  title: ཁེད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    EDEB:
      image_group_id: I1PD36308
      title: ''
      total_pages: 169
      order: 1
      base_file: EDEB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
